addSbtPlugin("com.timushev.sbt"          % "sbt-updates"              % "0.3.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.10")
addSbtPlugin("com.geirsson"              % "sbt-scalafmt"             % "1.5.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"             % "0.14.10")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager"      % "1.6.1")
